### ISSUE TITLE
LICENSE Not Retained From loglevelnext

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-log#11]
* Operating System: n/a
* Node Version: n/a
* NPM Version: n/a
* webpack Version: n/a
* webpack-dev-server Version: 2.0.0

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

n/a

### Expected Behavior

I would expect the LICENSE from loglevelnext to be included in this project.

### Actual Behavior

No LICENSE attribution exists. [This commit](https://github.com/webpack-contrib/webpack-log/commit/b5c2017e45b013a1b4c9e09694fc120afc3a307a) copied `loglevelnext` into the project, rather than using it as a dependency. The [LICENSE](https://github.com/shellscape/loglevelnext/blob/master/LICENSE) for `loglevelnext` states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

At present, this project is in violation of that clause.

### For Bugs; How can we reproduce the behavior?

n/a 

### For Features; What is the motivation and/or use-case for the feature?

n/a

**Comment by michael-ciniawsky** [comment]
https://github.com/shellscape/loglevelnext/blob/master/package.json#L5 Why not?

**Comment by alexander-akait** [comment]
@michael-ciniawsky all repos in `webpack` and `webpack-contrib` should be `JS Foundation` license, it is require

**Comment by evilebottnawi** [comment]
Also
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Can't be applied to MIT, @shellscape you are violating MIT license

**Comment by michael-ciniawsky** [comment]
The issue (to my understanding) was the missing copyright note which I added in #12. I don't have the MIT license in working memory and simply forgot 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This is stated by the MIT License and therefore adding a copyright note is a valid claim and it should be **fixed** by now...

> @michael-ciniawsky all repos in webpack and webpack-contrib should be JS Foundation license, it is require

The JS Foundation License is a MIT derivat, e.g we publish all packages as MIT to the `npm` registry

Was something missing in #12? Otherwise what's the issue here?

**Comment by alexander-akait** [comment]
@michael-ciniawsky MIT !== JS Foundation (they have same text, but they some difference). Also we can't get donate from JS Foundation for this project as example.

**Comment by michael-ciniawsky** [comment]
> MIT !== JS Foundation (they have same text, but they some difference)

same text, but different... This sounds entirely wrong. How is one supposed to know about these differences then? 

>  Also we can't get donate from JS Foundation for this project as example.

JS Foundation Donations? If you're talking about founding this is enterily handled via OpenCollective and unrelated to the JS Foundation to my knowledge but I also can't reliably tell nor should it be a concern here

Anyways... as long as I didn't miss anything in #12 all of the debate seems to unrelated to the issue (adding copyright note) in particular, so whatever the issue might be someone needs to elaborate as I'm not following

**Comment by alexander-akait** [comment]
@michael-ciniawsky 

> same text, but different... This sounds entirely wrong. How is one supposed to know about these differences then?

You can find all information about difference here https://cla.js.foundation/webpack/webpack

> JS Foundation Donations? If you're talking about founding this is enterily handled via OpenCollective and unrelated to the JS Foundation to my knowledge but I also can't reliably tell nor should it be a concern here

Some companies what donate through OpenCollective belong to JS Foundation and they require JS Foundation license to continue donate. OpenCollective is just platform for donation (donation can be done using other platforms/banks/payment system).

**Comment by dmethvin** [comment]
The JS Foundation [has a process](https://github.com/JSFoundation/TAC/blob/master/Project-Lifecycle.md#applying-to-join) for adopting projects. Copying the code into a JSF-supported organization while removing the old license (or inserting the JSF license) is definitely *not* the process. To ensure that we have the legal rights to the software, we need the author(s) to transfer ownership. 

> Some companies what donate through OpenCollective belong to JS Foundation and they require JS Foundation license to continue donate.

If donors are using the fact that this project is in a JSF repo as a justification to donate, then it is even more important to ensure we use the correct legal process.

> You can find all information about difference here https://cla.js.foundation/webpack/webpack

That is only saying that if a project doesn't have an explicit license then it is assumed to be Apache 2.0. Had this project gone through process and been accepted it would most likely have retained its MIT license. 

There is a lot of incorrect information in this thread, I'll call in @kborchers to see what needs to be done to clean things up.

**Comment by shellscape** [comment]
This is especially curious, as the code was copied and then released. The commit history for the files copied suggest that it doesn't appear to be a derivative work either, rather a redistribution under a different name. Also curious, that was done in a straight commit to master without peer review. And since it's a one-to-one copy, it's baffling why this was attempted to begin with.

Appreciate @dmethvin weighing in here. Of note, I was never approached about `loglevelnext` being absorbed into `webpack-contrib` nor about it being redistributed under a different name in `webpack-log`.

**Comment by michael-ciniawsky** [comment]
> The JS Foundation has a process for adopting projects. Copying the code into a JSF-supported organization while removing the old license (or inserting the JSF license) is definitely not the process. To ensure that we have the legal rights to the software, we need the author(s) to transfer ownership.

It's debatable if I actually 'adopted a project' here since I didn't fork the project directly into `webpack-contrib` with the intend to continue it as a separate project or the like but instead took the code (under MIT License) as an individual which accepted the CLA and committed it to this repo. While I was aware that transfering project **ownership** has a process in place I certainly wasn't for contributions which may include MIT licensed code from third-partys and still don't really understand what's the exact issue in doing so

But I will refrain from taking part in any further debate, so in case the changes I made weren't legal please someone explain which actions I need to take (if any) to resolve the issue

**Comment by dmethvin** [comment]
If the author of the code makes a pull request to a project and has signed the JSF CLA then they're making that contribution using the license of that project and there's no problem.

What seems to have happened here is that a large amount of someone else's code was copied from an outside project to this one without attribution, and without the license specified in their code.  So now it de-facto appears to have the JSF license (since it's in this repo) but is not code licensed to the JSF. You can't avoid having the JSF adopt someone else's project by copying the whole project source code into yours. 😄 

Can someone give some background about why the code was copied from an external project to this one? What was it about the old arrangement that was unacceptable?

**Comment by michael-ciniawsky** [comment]
@shellscape was a former contributor and author of packages within `webpack-contrib` (including this package), but abandoned them after a dispute with the webpack Core Team. @evilebottnawi and I took over maintenance of these projects and `webpack-log` in particular is currently used by the `webpack-dev-middleware` && `webpack-dev-server` which both rely on options based upon the API of `webpack-log`. This therefore would have made it more involved to replace the dependency on `loglevelnext` completely. Since `loglevelnext` is owned by @shellscape exclusively, potential bugfixes are impossible and in the worst case the dependency may even be a security risk, so the approach I took was to simply copy the code into `webpack-log` for the time being and call it a day. The code is licensed under MIT and seems to be a fork of `loglevel` itself exclusively made for `webpack-log` back in the day to begin with. 

> If the author of the code makes a pull request to a project and has signed the JSF CLA then they're making that contribution using the license of that project and there's no problem.

I though this is only needed if e.g I would have had access to the repo and transfered it + committed the license change myself. I made the contribution of MIT licensed code with a few stylistic nits (irrelevant) and also signed the CLA as a contributor, I certainly understand that this is not appreciated, but still the MIT License grants me (as the individual) the right to do so. This process should be documented better and maintainers should be instructed with the basics and where to reach out for help if in doubt 

> What seems to have happened here is that a large amount of someone else's code was copied from an outside project to this one without attribution,

Yes, besides the attribution (which I already 'fixed' in #12) I was under the impression that this wouldn't be an issue, since where my 'contribution' is coming from in the end should be **irrelevant** as long as I don't voilate any 'terms of use' of third-party code I intend to include and that's effectively **not** the case here, since the MIT license explicitly grants me those rights

> License (MIT)
> ...
> including without limitation the rights to use, **copy**, modify, merge, **publish**, distribute, **sublicense**, and/or sell copies of the Software,
> ...

>  and without the license specified in their code.

I don't think I actually need to do that for MIT licensed projects aswell, but if the attribution is insufficient I can simply fix it...

**Comment by shellscape** [comment]
> The code is licensed under MIT and seems to be a fork of loglevel itself exclusively made for webpack-log back in the day to begin with.

The assumption is false. The module was written during my time working for gilt.com, and was (maybe still is?) used for client-side logging on that platform. It was chosen as a dependency for this project because its purpose was apt.

> Since loglevelnext is owned by @shellscape exclusively, potential bugfixes are impossible and in the worst case the dependency may even be a security risk, so the approach I took was to simply copy the code into webpack-log for the time being and call it a day.

That is simply verbal horse manure, insulting, and disingenuous at best. No bugfix request has been made by either @michael-ciniawsky or @evilebottnawi to that project so the assertion is patently false.  It's mind boggling that this is trying to be justified, and It's pretty obvious that the motives for this weren't pure. This is a bad look for the committing author, for this project, and webpack as a whole.

As Dave points out, by including `loglevelnext` attribution within the same JSF License, it is implied that it is copyrighted under the same covenants as JSF projects, which it is not. If this project insists on foolhardily copying the code, rather than using the dependency like the rest of the ecosystem does, it should include the license from the project in the hilariously named `loglevel` directory residing with the copied files, or the files which were copied should include the copyright as a header in each file copied.

**Comment by alexander-akait** [comment]
@shellscape 

You are toxic guy, I have nothing to do with this project and I hear insults in my address. At this time, you are violating Code of Conduct. In fact, you simply ignored requests not to use third-party projects to which there will be no possibility for fixes and features. You ignored any feedback from the community and other developers and now blame everyone for problems. All you did was spend the money of developers/companies who donate/support use and left them with problems/errors/bugs in your code, blaming everyone for incompetence. It it not professionally. Instead of working together and creating something new, you insult, accuse and offend.
